title: Reference Site
description: Reference site using the Just the Docs theme!
theme: just-the-docs

url: https://franknunez23.github.io/

aux_links:
  Template Repository: https://franknunez23.github.io/reference/
